export const INDICATOR = {
  DEFAULT_BUY_RSI: 35,
  DEFAULT_SELL_RSI: 65,
  DEFAULT_BUY_MFI: 35,
  DEFAULT_SELL_MFI: 65,
  DEFAULT_BUY_MACD: -0.5,
  DEFAULT_SELL_MACD: 0.6,
} as const;

export const PRICE = {
  GUKBAP: 8000,
  CHICKEN: 18000,
  COFFEE: 4500,
};
